### ISSUE TITLE
Suspect parsing of the packfile

### ISSUE THREAD

**Issue by FintanH** [GitoxideLabs/gitoxide#972] opened 2023-08-08 14:24 UTC
### Duplicates

- [X] I have searched the existing issues

### Current behavior 😯

I'm running up against some issues when it comes to the fetch protocol and the `packfile`, in particular. I'm hoping to paint the picture here and see if you might have any ideas on what might be going on and whether it could be my side or something going on inside `gix-protocol` :)

The setup is using the V2 protocol so that we have lots of control over staging a fetch, doing some business logic, and then staging a further fetch. We decided to crib a lot of the fetch functionality, since our setup is a bit unique and we wanted to avoid any extra moving parts that weren't relevant to us -- so the following is the definition of the fetch in `heartwood` https://github.com/radicle-dev/heartwood/blob/gix-fetch-base/radicle-fetch/src/transport/fetch.rs#L174-L179. Now, a lot of it will look familiar to https://github.com/radicle-dev/heartwood/blob/gix-fetch-base/radicle-fetch/src/transport/fetch.rs#L258-L262. That is until I ran into my first issue with the protocol, the flush packet during the `packfile` parsing wasn't being read and so when a following `ls-refs` command was sent it would immediately read the flush packet and think it was done. To remedy this, I added [these lines](https://github.com/radicle-dev/heartwood/blob/gix-fetch-base/radicle-fetch/src/transport/fetch.rs#L258-L262). I'm wondering if you have any idea why the packfile reader wouldn't go until it finds the flush packet?

Once I had this running, I was executing part of our test suite which runs many fetches in parallel. Strangely, a random set of tests would often fail, and again it was to do with the `packfile` parsing. A fetch would fail with the message:
```
Failed to decode the first four hex bytes indicating the line length: Invalid character '\u{2}' at position 0
```
I believe what it was trying to parse was `"\u{2}Tot"`, which, my guess, is that it's part of the progress message from the previous fetch. So again, the `packfile` parsing seems to be exiting early and not parsing all the messages.

I hope all that makes sense. If you need more context let me know! Also happy to hop on a call if you have the time :blush: 

### Expected behavior 🤔

Parsing the `packile` should exhaust the messages and exit upon the receiving of the flush packet.

### Steps to reproduce 🕹

You should be able to reproduce in `heartwood` running `cargo test -p radicle-node tests::e2e` but not sure if you'll know what's going on with the output :sweat_smile:

**Comment by Byron** [comment] 2023-08-08 16:40
Thanks for reaching out, even though it's probably close to impossible to tell what's going on without spending considerable time to get going here.

As for the error message, I agree that it seems to see a sideband while not expecting one, but what's puzzling is how it could try to decode something that starts with a 2 - it looks like a sideband progress, but first of all it should see a 4 hex characters as part of the packetline. Somehow the packetline gets decoded once, and then once more?

>  Also happy to hop on a call if you have the time 😊

I sent an email for that.

**Comment by Byron** [comment] 2023-08-10 13:38
Thanks for the fun catchup!

I take away that somehow, a flush package remains in the underlying reader, possibly paired with a progress message prior to that.

What's strange is that to the code that writes the back to disk and resolves it, the pack stream is exposed as `Read` which ends naturally once the underlying [StreamingPeekableIter](https://docs.rs/gix-packetline/0.16.4/gix_packetline/struct.StreamingPeekableIter.html) sees a flush packet. And it's because the underlying reader saw the flush package that it can stop the read. There are tests that repeatedly read various blocks from a packet-line encoded stream, each separated by a flush packet, that seem to work as expected.

So the question remains: How come that the flush packet isn't consumed, or…that the remote is sending another flush package right after? How come that sometimes a progress message is in there as well, even though that's seemingly unrelated?

To understand better what's going on, one could configure the transport to use a proxy server, or one could configure the server side/`git` binary to echo packetlines. Ideally, one would find a way to see all communication that's going on between the client and the server, and when a failing interaction is found, the intercepted data can be used to fabricate a test which hopefully leads to a reproduction.

*I also checked the code [that implements `Read/BufRead`*](https://github.com/Byron/gitoxide/blob/2578e576bfa365d194a23a1fb0bf09be230873de/gix-packetline/src/read/sidebands/blocking_io.rs#L134-L203) and it doesn't seem to be able to leave data unconsumed either, so getting a test should be the way to go*. So once there is some time after the current priority, I will see if I can create test that for starters does to fetches in a row on the same connection, as such a test doesn't exist yet.

**Comment by FintanH** [comment] 2023-11-09 12:43
I gave this a shot and removed the custom logic for checking for the flush packet and it failed. When I put the custom logic back, everything passed again -- so my conclusion is that this is likely not the fix, unfortunately.

We're essentially using the Git `Connection` found in `gix-transport`: https://app.radicle.xyz/nodes/seed.radicle.xyz/rad:z3gqcJUoA1n9HaHKufZs5FCSGazv5/tree/radicle-fetch/src/transport.rs#L184

**Comment by Byron** [comment] 2023-11-09 14:20
Thanks so much for trying it out, it would surely have been nice if it would just have worked :).

And since there is no custom transport I'd assume that `Connection` should just work as advertised (if it has anything to do with that).
I hope to find out what it is though, as this issue is next up on my list, so hope to get to it in the next couple of days.

**Comment by Byron** [comment] 2023-11-12 12:21
I have posted a fix for this [in the related PR](https://github.com/radicle-dev/heartwood/pull/556) over at `heartblood`, which indeed has to be made on the call-side.
In short, it's the same fix but using facilities of the `reader` instead of operating on the bare 'wire' - all other details are in the PR itself.

**Comment by Byron** [comment] 2024-10-18 12:46
I think this can be closed and the PR referenced in the comment above has all the details.

**Closed as completed by Byron** 2024-10-18 12:46 UTC
Labels: acknowledged
